apiVersion: v1
kind: Namespace
metadata:
  name: surveyjs
  annotations:
    fairwinds.com/insights-skip: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: artifacts-ssk8s-vibrenthealth-com-vibrent-base-read-only
  namespace: surveyjs
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiYXJ0aWZhY3RzLnNzazhzLnZpYnJlbnRoZWFsdGguY29tIjogeyJhdXRoIjogImNtOWliM1FrY21WaFpDMWhiR3c2VWpSU1UwUlZlVGRoZVRoMGJXTjBaV3BMVjFnPSJ9fX0=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveyjs-app
  namespace: surveyjs
  annotations:
    fairwinds.com/insights-skip: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: surveyjs
  template:
    metadata:
      labels:
        app: surveyjs
    spec:
      containers:
        - name: surveyjs
          image: artifacts.ssk8s.vibrenthealth.com/vibrent-base/surveyjs-frontend:10
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: artifacts-ssk8s-vibrenthealth-com-vibrent-base-read-only
---
apiVersion: v1
kind: Service
metadata:
  name: surveyjs-service
  namespace: surveyjs
spec:
  selector:
    app: surveyjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
