apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
  namespace: surveyjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: artifacts.ssk8s.vibrenthealth.com/vibrent-base/surveyjs-backend:2
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "mysql+pymysql://user:password@mysql.surveyjs.svc.cluster.local:3306/surveydb"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: surveyjs
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
